numDelegates: 24
numCandidateDelegates: 36
numSubEpochs: 15
numSubEpochsDardanelles: 30
dardanellesHeight: 100081
dardanellesOn: true
fairbankHeight: 3252241
consensusScheme: "ROLLDPOS"
rangeQueryLimit: 100
rewardPortionCfg:
  rewardPortionContract: "io1ktrmwyqcu6d6l403ag6gkjtmlq60nv9qp72zpe"
  rewardportionContractDeployHeight: 3653543
genesis:
  account:
    initBalances:
      io1yrzvkucxpytn4fru35lc8r8jk4jtue4syg8d4h: "800000000000000000000000000"
      io120au9ra0nffdle04jx2g5gccn6gq8qd4fy03l4: "7000000000000000000000000000"
      io10t7juxazfteqzjsd6qjk7tkgmngj2tm7n4fvrd: "1000000000000000000000000000"
poll:
  skipManifiedCandidate: true
  voteThreshold: "100000000000000000000"
  scoreThreshold: "0"
  selfStakingThreshold: "0"
gravityChain:
  gravityChainStartHeight: 7614500
  gravityChainAPIs:
    - https://mainnet.infura.io/v3/e1f5217dc75d4b77bfede00ca895635b
  registerContractAddress: 0x8619a5c5232c32bae63c442b905a27ae46598566
  rewardPercentageStartHeight: 8300000
rewarding:
  numDelegatesForEpochReward: 100
  numDelegatesForFoundationBonus: 36
  productivityThreshold: 85
  exemptCandidatesFromEpochReward:
    - "696f726f626f746270303031"
    - "696f726f626f746270303032"
    - "696f726f626f746270303033"
    - "696f726f626f746270303034"
    - "696f726f626f746270303035"
    - "696f726f626f746270303036"
    - "696f726f626f746270303037"
    - "696f726f626f746270303038"
    - "696f726f626f746270303039"
    - "696f726f626f746270303130"
    - "696f726f626f746270303132"
    - "696f726f626f746270303131"
    - "696f726f626f746270303331"
    - "696f726f626f746270303332"
    - "696f726f626f746270303333"
    - "696f726f626f746270303334"
    - "696f726f626f746270303335"
    - "696f726f626f746270303336"
    - "696f726f626f746270303133"
    - "696f726f626f746270303134"
    - "696f726f626f746270303135"
    - "696f726f626f746270303136"
    - "696f726f626f746270303137"
    - "696f726f626f746270303138"
    - "696f726f626f746270303139"
    - "696f726f626f746270303230"
    - "696f726f626f746270303231"
    - "696f726f626f746270303232"
    - "696f726f626f746270303233"
    - "696f726f626f746270303234"
    - "696f726f626f746270303235"
    - "696f726f626f746270303236"
    - "696f726f626f746270303237"
    - "696f726f626f746270303238"
    - "696f726f626f746270303239"
    - "696f726f626f746270303330"

hermesConfig:
  hermesContractAddress: "io1fqulsuv8p820wmr0yd39jzx0m3pnpmuzzcywh8"
  multiSendContractAddressList:
    - "io1lvemm43lz6np0hzcqlpk0kpxxww623z5hs4mwu"
    - "io16y9wk2xnwurvtgmd2mds2gcdfe2lmzad6dcw29"
voteWeightCalConsts:
  durationLg: 1.2
  autoStake:  1
  selfStake:  1.06
